---
.travis.yml:
  secure_global_env:
    # PUBLISHER_PASSWORD
    - "Dm3y5HRGBs9VyqIAHAVbgETJjoeNfM9P4Og4foN5r1T3r7KvjGh/a6X61kCK\nCYZU9v60McoFVnaWbCX6a0duoLplqEA5RiJlfgiay8Fry4ROZTvwNbZWhlqJ\nxeXmUMZca7CgYbiKRoxVSwBirKPX26enaAgIArBQXdenoQdO6Eo="
